config/routes.rb
Rails.application.routes.draw do
  
  resources :articles

  root 'articles#new'

  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def new
	end

	def index
		@articles = Article.all 
	end

	def show
		@article = Article.find(params[:id])
	end

	def create
		@article = Article.new(params.require(:article).permit(:title, :text))

		@article.save
		redirect_to @article
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
	end

	def create
		@user = User.new(params.require(:user).permit(:name, :first_name))

		@user.save
		redirect_to @user 
	end

	def show
		@user = User.find(params[:id])
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
	<tr>
		<th>Title</th>
		<th>Text</th>
	</tr>

	<% @articles.each do |article| %>
	<tr>
		<td><%= article.title %></td>
		<td><%= article.text %></td>
		<td><%= link_to 'Show', article_path(article) %></td>
	</tr>
	<% end %>
</table>

app/views/articles/new.html.erb
<h1> New Article </h1>
<%= form_for :article, url: articles_path do |f| %>
	<p>
		<%= f.label :titre %><br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :text %><br>
		<%= f.text_area :text %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<%end %>

app/views/articles/show.html.erb
<p>
	<strong> Title:</strong>
	<%= @article.title %>
</p>

<p>
	<strong>Text:</strong>
	<%= @article.text %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1> New User </h1>
<%= form_for :user, url: users_path do |f| %>
	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.label :first_name %><br>
		<%= f.text_field :first_name %>
	</p>

	<p>
		<%= f.submit %> 
	</p>

<% end %>

app/views/users/show.html.erb
<p> 
	<strong> Your name</strong>
	<%= @user.name %>
</p>

<p>
	<strong> Your first name</strong>
	<%= @user.first_name %>
</p>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>